name: Bump
run-name: Bump ${{ github.ref_name }}, by ${{ github.actor }}
on:
  release:
    branches:
      - stable
    types:
      - published
jobs:
  bump:
    name: Bump
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BRANCH: stable
    steps:
      - uses: actions/checkout@v4
      - uses: dcarbone/install-jq-action@v2.1.0
      - uses: actions/setup-node@v4
        with:
          node-version: lts/iron
      - name: Setup git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git fetch origin $BRANCH
          git checkout $BRANCH
          git pull origin $BRANCH
      - name: Bump version
        run: |
          echo "Bumping version to ${{ github.event.release.tag_name }}"
          npm version "${{ github.event.release.tag_name }}" -m "[skip ci] Release %s" --allow-same-version
      - name: Verify version
        run: jq -r '.version' package.json
      - name: Push changes
        run: git push origin $BRANCH
